"""Headline result: the same solves at a lower generation cost, and exactly which tasks move.

Panel A  the discordant tasks only: baseline -> CBE solve count per task, labelled by task ID,
         with the number of unchanged tasks stated once
Panel B  output tokens generated by each arm, annotated with the relative change
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plotting import LOCKED_RUNS, RC, attempts, locked_receipt, save
from theme import GRID, INK_SOFT
import viz

CLAIM = ("CBE solves the same number of held-out attempts while generating 13.7% fewer output "
         "tokens, and only 15 of 89 tasks change outcome in either direction.")


def task_rows(data: dict[str, Any]) -> list[dict[str, Any]]:
    out = []
    for task in sorted(data):
        base = [int(r["reward"]) for r in data[task].get("baseline", []) if r["reward"] is not None]
        cbe = [int(r["reward"]) for r in data[task].get("science", []) if r["reward"] is not None]
        if not base or not cbe:
            continue
        out.append({"task": task, "base_rate": sum(base) / len(base), "cbe_rate": sum(cbe) / len(cbe),
                    "base": sum(base), "cbe": sum(cbe), "n_base": len(base), "n_cbe": len(cbe),
                    "replicates": len(base)})
    return out


def movers(ax: Any, data_rows: list[dict[str, Any]]) -> dict[str, int]:
    gains = [r for r in data_rows if r["cbe_rate"] > r["base_rate"]]
    losses = [r for r in data_rows if r["cbe_rate"] < r["base_rate"]]
    unchanged = len(data_rows) - len(gains) - len(losses)
    for row in data_rows:
        row["delta_pp"] = (row["cbe_rate"] - row["base_rate"]) * 100
    losses.sort(key=lambda r: r["delta_pp"])
    gains.sort(key=lambda r: r["delta_pp"])
    ordered = losses + gains
    ys = list(range(len(ordered)))

    for y, row in zip(ys, ordered):
        kind = "gain" if row["delta_pp"] > 0 else "loss"
        ax.barh([y], [row["delta_pp"]], height=0.55, color=viz.COLOUR[kind], edgecolor="white",
                linewidth=0.5, zorder=2)
        offset = 3.5 if row["delta_pp"] > 0 else -3.5
        ax.text(row["delta_pp"] + offset, y, f"{row['delta_pp']:+.0f}", va="center",
                ha="left" if row["delta_pp"] > 0 else "right", fontsize=6.9,
                color=viz.COLOUR[kind], fontweight="bold", clip_on=True)

    ax.axvline(0, color=GRID, lw=0.7, zorder=1)
    ax.set_yticks(ys)
    ax.set_yticklabels([row["task"] for row in ordered], fontsize=6.9)
    ax.set_ylim(-0.75, len(ordered) - 0.25)
    ax.set_xlim(-96, 122)
    ax.set_xticks([-60, -30, 0, 30, 60, 90])
    ax.set_xlabel("CBE minus baseline solve rate per task (pp)", fontsize=7.2)
    ax.grid(axis="x", color=GRID, lw=0.45, zorder=0)
    ax.set_ylabel("task", fontsize=7.2)
    viz.baseline_axis(ax)
    return {"gains": len(gains), "losses": len(losses), "unchanged": unchanged}


def tokens(ax: Any, receipt: dict[str, Any]) -> None:
    arms = ("baseline", "science")
    totals = [receipt["totals"][arm]["output_tokens"] / 1e6 for arm in arms]
    per_attempt = [receipt["totals"][arm]["output_tokens"]
                   / receipt["totals"][arm]["attempts_verified"] / 1000 for arm in arms]
    for index, (total, attempt, kind) in enumerate(zip(totals, per_attempt, ("baseline", "gain"))):
        ax.bar([index], [total], width=0.46, color=viz.COLOUR[kind], edgecolor="white",
               linewidth=0.5, zorder=2)
        ax.text(index, total + 0.20, f"{total:.2f}M", ha="center", va="bottom", fontsize=7.4,
                color=viz.COLOUR[kind], fontweight="bold")
    change = (totals[1] / totals[0] - 1) * 100
    ax.text(1, totals[1] - 1.6, f"{change:.1f}%", fontsize=7.4, color="white",
            fontweight="bold", ha="center", va="top")
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["baseline", "CBE"], fontsize=7.4)
    ax.set_xlim(-0.5, 1.5)
    ax.set_ylim(0, max(totals) * 1.30)
    ax.set_ylabel("output tokens, 522 attempts (M)", fontsize=7.2)
    viz.baseline_axis(ax)
    ax.grid(axis="y", color=GRID, lw=0.45, zorder=0)


def main() -> None:
    data = attempts(LOCKED_RUNS)
    receipt = locked_receipt()
    with plt.rc_context(RC):
        fig = viz.figure(5.5, 2.6)
        left = fig.add_axes((0.085, 0.155, 0.520, 0.655))
        right = fig.add_axes((0.735, 0.155, 0.250, 0.655))
        counts = movers(left, task_rows(data))
        tokens(right, receipt)
        viz.panel(left, "A", "Tasks that change outcome")
        viz.panel(right, "B", "Generation cost")
        save(fig, "fig_parity", claim=CLAIM)
    print(f"  movers: {counts}")


if __name__ == "__main__":
    main()
